Advanced redux
khali16/burger pull request #7
Opened 2021-04-08 13:04 UTC by khali16

DODAŁAM Z MAKSIEM REDUXA DO BURGERA

2021-04-08 14:43 UTC, airycanine requested changes

2021-04-08 14:43 UTC, airycanine commented on src/components/Navigation/NavigationItems/NavigationItems.js
>  const navigationItems = (props) => (
destructure props

2021-04-08 14:43 UTC, airycanine commented on src/components/Order/CheckoutSummary/CheckoutSummary.js
> +const checkoutSummary = (props) => {
destructurize props pls

2021-04-08 14:43 UTC, airycanine commented on src/components/Order/CheckoutSummary/CheckoutSummary.js
> +      <div style={{ width: "100%", margin: "auto" }}>
try not to use inline styles when possible

2021-04-08 14:43 UTC, airycanine commented on src/components/Order/CheckoutSummary/CheckoutSummary.js
> +        CANCEL
avoid using static strings, extract them to variables instead - create constants/texts.js file which will hold them

2021-04-08 14:43 UTC, airycanine commented on src/components/Order/CheckoutSummary/CheckoutSummary.js
> +        CONTINUE
avoid using static strings, extract them to variables instead - create constants/texts.js file which will hold them

2021-04-08 14:43 UTC, airycanine commented on src/components/Order/Order.js
> +          ZŁOCISZE POLSKIE {Number.parseFloat(props.price).toFixed(2)}{" "}
1.Create a directory for util functions
2.Create a file called numberUtils.js in it
3. extract this 'Number.parseFloat(props.price).toFixed(2)' to separate util functions in numberUtils.js

2021-04-08 14:43 UTC, airycanine commented on src/components/UI/Input/Input.js
> +  let inputElement = null;
probuj unikac takich przypisan, zazwyczaj da sie to lepiej zrobic. np. w twoim przypadku moglabys wynieść switcha (19-73) do osobnej funkcji ktora bedzie zwracala input element i jedynie zrobic

const inputElement = funkcjaZeSwitchem()

2021-04-08 14:43 UTC, airycanine commented on src/components/UI/Input/Input.js
> +  }
Dobrą praktyka jest wynoszenie takich switchy do osobnych funkcji, jest czysciej w ten sposob ;)

2021-04-08 14:43 UTC, airycanine commented on src/containers/BurgerBuilder/BurgerBuilder.js
> +    return sum > 0; //jeśli jest większe od 0 to ustawi teog statea na true
prosze unikac polskiego :))

2021-04-08 14:43 UTC, airycanine commented on src/containers/BurgerBuilder/BurgerBuilder.js
> +    if (this.props.ings) {
Nie uzywaj skroconych nazw, ings nic nie znaczy. Ingredents bylo lepsze.
Jesli nie mozesz uzyc ingredients jako nazwy to pokombinuj, zeby nadal bylo czytelne i od razu bylo wiadomo o co kaman.
np. foodIngredients czy cos tkaeigo

2021-04-08 14:43 UTC, airycanine commented on src/containers/Checkout/Checkout.js
> +    let summary = <Redirect to="/" />;
raczej unikaj letów i takiego przypisywania zaleznie od warunków, jest to mniej czytelne. Ja bym zrobil tak:
```
resolveSummary = () => (
  this.props.ings ? 
          <div>
            {this.props.purchased &&  <Redirect to="/" />}
            <CheckoutSummary
              ingredients={this.props.ings}
              checkoutCancelled={this.checkoutCancelledHandler}
              checkoutContinued={this.checkoutContinuedHandler}
            />
            <Route
              path={this.props.match.path + "/contact-data"}
              component={ContactData}
            />
          </div>
      
   :   <Redirect to="/" />
)
```

2021-04-08 14:43 UTC, airycanine commented on src/containers/Checkout/Checkout.js
> +    return summary;
i tutaj wtedy return resolveSummary()

2021-04-08 14:43 UTC, airycanine commented on src/containers/Checkout/Checkout.js
> +    ings: state.burgerBuilder.ingredients,
zrenamuj prosze na cos ladnego, np. burderIngredients

2021-04-08 14:43 UTC, airycanine commented on src/containers/Checkout/ContactData/ContactData.module.css
> +  .Cipa {
to niezla Cipa

2021-04-08 14:43 UTC, airycanine commented on src/store/actions/burgerBuilder.js
> +        "https://react-my-burger-b878c-default-rtdb.firebaseio.com/ingredients.json"
wynieś to proszę do osobnego consta w constants/endpoints.js

2021-04-12 10:08 UTC, khali16 commented on src/containers/Checkout/ContactData/ContactData.module.css
> +  .Cipa {
xD

2021-04-12 10:10 UTC, merged